### ISSUE TITLE
[master] MQT: Status red

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#173]
![descarga 4](https://cloud.githubusercontent.com/assets/6644187/6954321/97c09804-d88d-11e4-91b7-d6b2554b554f.png)

**Comment by dreispt** [comment]
The MQT tests for 7.0 and 6.1 are failing - it seems that something is is now incompatible with those Odoo versions.

I believe it is caused by the [test dependency](https://github.com/OCA/maintainer-quality-tools/commit/b43cc487c02c9b927eb527d6b26727e00f0f0df7#diff-08357642cfa8d94d6869b876051508beR4) on `partner-contact` for v8.
It should be removed from the `test_repo`.
