### ISSUE TITLE
Add a script that pulls Transifex translations

### ISSUE THREAD

**Issue by Ehtaga** [OCA/maintainer-quality-tools#192]
Now that translation files are automatically pushed to Transifex via Travis, it would be interesting to write a script for an automatic pull.

The export is described here: [PR#186](https://github.com/OCA/maintainer-quality-tools/pull/186).

The [txclib](https://pypi.python.org/pypi/transifex-client) library contains this pull command. The steps would be:
* `tx init` 
* `tx set` 
* `tx pull`

The first two commands are detailed in [PR#186](https://github.com/OCA/maintainer-quality-tools/pull/186).

The .tx folder created by the `tx init` command should be ignored by git (otherwise it would disturb the export part).
Once the translation files are updated, they should be automatically pushed to the Github project.

This pull script can be runned periodically.

**Comment by pedrobaeza** [comment]
Hi, Agathe, I think this should be handled only when there's a modification on translated strings, or we end up with a lot of empty or garbage commits.

In my transbot proposal, I check for the changes storing a hash of the strings and comparing afterwards: https://github.com/OCA/server-tools/pull/76. As this was a complete system, the original translation hash was stored when the translation is uploaded, so now that the translation is done on the Travis script, we have to find another way, but it can be done with an initial push + storing hash.

The only drawback of this method is that is slow, because Transifex doesn't offer any good method for retrieving information about the changes done.

**Comment by bwrsandman** [comment]
How about this:

Run weekly, for each transifex project under OCA:
For each language
1. diff the *.po files ignoring the date, translator parts and term order
2. if there is a disparity or the language is new, add the lang to a list of things to commit
If there is something in the list, create a commit and push

**Comment by pedrobaeza** [comment]
But that can't be done if you don't query explicitly for each resource and each language, so the slowness is the same.

**Comment by max3903** [comment]
https://github.com/OCA/maintainer-tools/pull/63
