### ISSUE TITLE
Travis tests server for Transifex tests on pull requests

### ISSUE THREAD

**Issue by bwrsandman** [OCA/maintainer-quality-tools#219]
Example: https://travis-ci.org/OCA/l10n-canada/jobs/73922706

Line culprit: https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_run_tests#L67
```python
    if tests_unspecified and not lint_check_enabled:
        tests.append(['test_server.py'])
```

Should be more like 
```python
    if tests_unspecified and not lint_check_enabled or (transifex_enabled and not is_pull_request):
        tests.append(['test_server.py'])
```

**Comment by pedrobaeza** [comment]
I don't think this is really a bug, because it only happens in a bad travis configuration. The line will only be activated if `tests_unspecified` is set, and this is only happen when you haven't set `TESTS` environment variable, and this is not the case on correct travis files like the one currently present on l10n-canada: https://github.com/OCA/l10n-canada/blob/8.0/.travis.yml#L17 and https://github.com/OCA/l10n-canada/blob/8.0/.travis.yml#L23

**Comment by moylop260** [comment]
@bwrsandman 
Is a open issue still?

**Comment by bwrsandman** [comment]
I don't know. Haven't looked at it recently. You can close it.

**Comment by moylop260** [comment]
@bwrsandman 
Thanks
