### ISSUE TITLE
Enable JS coverage

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#290]
Somebody knows how to enable coverage of javascript?

**Comment by dreispt** [comment]
Maybe @hbrunn can help.

**Comment by lasley** [comment]
Assuming this is similar to coverage in a normal JS lib & not something insanely Odoo specific, I can likely help here once we get support for multiple languages per repo.

**Comment by lasley** [comment]
Alright reviving this now that we can have multiple language support due to CodeCov.

I'm almost positive I can get us coverage reporting, but I only know how to do this with Instanbul paired with a Test Runner like Karma or Grunt. 

Looking at the Odoo source, I think our key is the fact that [Odoo also uses Grunt](https://github.com/odoo/odoo/blob/7682760dcad232829fbb5d4221f66a1ebb9d6c91/addons/web/Gruntfile.js#L3). The requirements boil down to using something like this - https://github.com/afonsof/grunt-qunit-cov

**Comment by moylop260** [comment]
Excellent
Good to know
Thank you!

**Comment by pedrobaeza** [comment]
Any update on this?

**Comment by moylop260** [comment]
@lasley comment us that this feature require too much patches to odoo core.
(Could you help me to explain it better @lasley )

**Comment by lasley** [comment]
All solutions I can find at this point involve injecting data into the [Odoo Gruntfile](https://github.com/odoo/odoo/blob/7682760dcad232829fbb5d4221f66a1ebb9d6c91/addons/web/Gruntfile.js#L3). I'm at a loss on how to do this without completely re-implementing the file, or dirty patches with SED 😦

**Comment by hbrunn** [comment]
can't you wrap `module.exports` into a function that passes a fake grunt object to the original, records/passes through what Odoo's gruntfile does, and adapts afterwards the way we need it?

**Comment by lasley** [comment]
Hmmmmmm I feel like I should have tried this, but I'm almost positive I haven't now that you say it. Will report back!

**Comment by nhomar** [comment]
I think thi sissue can be closed, this is working already AFAICR, open it again if not.

**Comment by pedrobaeza** [comment]
No, this is not working. One thing is JS linter. Another is the test coverage. It's even more important in v11 now that QUnit allows to test better JS widgets and interface.

**Comment by yelizariev** [comment]
Simple solution I use myself:
https://github.com/it-projects-llc/pylint-odoo/commit/00b068817724ec756b1425356f178705200c12e7
It only checks whether there is any js coverage and makes warning otherwise

**Comment by nhomar** [comment]
thank U @yelizariev can you please make a PR in order to have that available, and elaborate a little bit more in your solution?

@yelizariev Reading what @pedrobaeza  is saying is right this is for coverage, your solution is **lints** do I understand properly?

@pedrobaeza tehre is a link to codecov merged here: https://github.com/OCA/maintainer-quality-tools/pull/342. isn't it solving the issue?

@pedrobaeza I think we should threat the V11.0 in a separate thread, the technology is different, and several other things that must be considered, Don't you thinK?

**Comment by pedrobaeza** [comment]
Still is not the same, Nhomar. You want to check the JS code coverage. Nothing to do with 11.0, Python 2 or Python 3.

It's notable to say that v11 includes a new JS QUnit framework for helping testing the JS widgets, but again it's complementary.
