### ISSUE TITLE
project without oca_dependencies.txt fail with module not found by PR #289

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#291]
FYI https://github.com/OCA/maintainer-quality-tools/pull/289 now show a error of `module not found.`
Now all projects required `oca_dependencies.txt` instead of `git clone ...` in `.travis.yml`

**Comment by moylop260** [comment]
Example:
https://github.com/OCA/rma/pull/55

**Comment by guewen** [comment]
oops...
ok, it is because the git clone is still hardcoded in `travis.yml`:

```
git clone --depth=1 https://github.com/OCA/crm -b ${VERSION} $HOME/crm
git clone --depth=1 https://github.com/OCA/stock-logistics-workflow -b ${VERSION} $HOME/stock-logistics-workflow
```
And now they are no longer in `$HOME` but in `$HOME/dependencies`.
So I'm sorry for the regression, I didn't expected projects to have hardcoded clones.

Don't you think we should take this opportunity to clean the repositories?

**Comment by osvalr** [comment]
@moylop260 @guewen, I just made a PR for OCA/rma [here](https://github.com/OCA/rma/pull/63) to get solved this issue there ```oca_dependencies.txt```

**Comment by moylop260** [comment]
@guewen 
+1 to take this opportunity to clean the repositories, adding `oca_dependencies.txt`

**Comment by moylop260** [comment]
@guewen 
Could you send a email to community list?
