### ISSUE TITLE
PyLint false positive

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#369]
Spotted at  https://travis-ci.org/OCA/l10n-portugal/jobs/164632922
Lots of pylint messages but pylint status is green!

**Comment by pedrobaeza** [comment]
That's because they are warnings, not errors. We can see if any of them should be promoted to real errors that switch Travis to red.

**Comment by dreispt** [comment]
We're much less aggressive than I though, then... 🤔

**Comment by pedrobaeza** [comment]
Yeah, that's because several people complain about the new checks introduced turned red Travis with simple changes that don't involve the affected modules, so 2 things were decided:

- To put several things as warnings, not as errors.
- To make several checks only on affected modules, not on all the repository.

As said, maybe we can discussed to raise some of the warnings as errors. For example, the warning about tabs instead of spaces can be considered an error.
