### ISSUE TITLE
Help Needed: l10n_generic_coa autoinstall in preinstalled and brakes l10n_xx testing

### ISSUE THREAD

**Issue by blaggacao** [OCA/maintainer-quality-tools#412]
For one of the following reasons:
```
Searching 24474 files for "l10n_generic_coa" (regex)

odoo-cc\addons\account\__init__.py:
   23                  module_list.append('l10n_' + country_code.lower())
   24              else:
   25:                 module_list.append('l10n_generic_coa')
   26          if country_code == 'US':
   27              module_list.append('account_plaid')

odoo-cc\addons\l10n_us\__openerp__.py:
    9  ==================================
   10      """,
   11:     'depends': ['l10n_generic_coa', 'report'],
   12      'data': [
   13          'data/res_company.xml',

```
`l10n_generic_coa` is installed although the list of preinstalled modules looks like this:
```
Modules to preinstall: ['website', 'account_bank_statement_import', 'product', 'account_reports', 'account_tax_adjustments', 'account_asset', 'sale', 'l10n_co_geo', 'account_tax_python', 'purchase', 'point_of_sale', 'base', 'stock_account', 'report', 'mail', 'hr_payroll_account', 'account', 'stock', 'hr_payroll', 'crm']
```
this then breaks in `l10n_co`
```yaml
-
  !python {model: account.chart.template, id: l10n_co_niif.configurable_chart_template}: |
    self[0].try_loading_for_current_company()

```
which in turn breaks data modules, that make reference to the newly created accounts making use of the `1_account_123` (account) <-> `account_123` (template) parity.

What can we do?

**Comment by blaggacao** [comment]
As we are dealing with the chicago warehouse, it's definitely the second cause (`l10n_generic_coa` being a dependency of `l10n_us`)

**Comment by blaggacao** [comment]
@qdp-odoo probably you should have a look at this, too. While testing is nos to common among localisations, it should not be made almost impossible by this.

Currently I see 2 workarounds:

1. Patch core and get this line out of the way `<field name='country_id' ref='base.us'/>`
2. Make a single repo/module as external dependency for all localisations, which only depends on base, has `autoinstall=True` and overrides this line.

**Comment by pedrobaeza** [comment]
Why don't you overwrite in your l10n_co module the country of the company to be Colombia?

**Comment by moylop260** [comment]
I had the same problem.
The first step was add to `l10n_XX` the country of the company to be`XX` (like as @pedrobaeza commented)
The problem is that the module `account` is installed previously because we need the depends to `account` from `l10n_XX`
Then we have a `openerp_template` database where `account` and `l10n_generic_coa` are installed.

I try many solutions but the last one was a ugly one because this problem is migrated to production too 😞 

I mean, we need force create a the database with country changed before of install `account` module but we don't want change our current deploy scripts...

Then my ugly solution was the following module [company_country](https://github.com/Vauxoo/server-tools/blob/10.0/company_country) feel free of migrate it to OCA or discuss new ideas.

**Comment by blaggacao** [comment]
@moylop260 Exactly, that describes the problem exhaustively. I'm also in favor of calling out to Quentin, if he can help us out. It should be possible to check `if threading.currentThread().testing != True` without further impediments. I guess, odoo would probably need to refactor their standard setup in order to trigger the standard tests, which depend on l10n_generic_coa, indeed. Until then a patch on core does the trick for us.

**Comment by blaggacao** [comment]
You can back it on https://github.com/odoo/odoo/pull/15004 ❤️

**Comment by jjscarafia** [comment]
Hi, we face the same situation in argentina, what we have done:
1. We have a [l10n_ar_base](https://github.com/ingadhoc/odoo-argentina/blob/9.0/l10n_ar_base/demo/res_company_demo.xml) module that set main company to argentina
2. This module also modify the odoo [auto install](https://github.com/ingadhoc/odoo-argentina/blob/9.0/l10n_ar_base/__init__.py) so it install our chart of account (l10n_ar_chart) and not the odoo one (l10n_ar)
3. For the pre-installation of account made by travis we have made a horrible thing that is to include autoinstalled modules so they are loaded to be tested and not auto-installed (you can see it [here](https://github.com/ingadhoc/odoo-argentina/blob/9.0/.travis.yml#L83))

I think a good approach would be to add an option to mqt like "NO_PRE_INSTALL" so you can exclude any list of modules of being pre-installed. What do you think about it?

**Comment by Imbatke** [comment]
Before,I have mistack but to time to time again and i go to play my profil to githubs.

**Comment by blaggacao** [comment]
@jjscarafia Last paragraph won't work probably. How should `NO_PRE_INSTALL` interfere with the database at the right moment (where `to install` is set). Ceterum censeo, this should be solved upstream. So maybe showing some decent love on the referenced PR would help...

**Comment by blaggacao** [comment]
**Findings - what I did**
- Patch core, moving base company no-mans-land (=`None`)
- We install the language at some point before account
- `l10n_co` is automatically installed (guess: learning a language saves us from no-mans-land)
- You might want that or not. I don't. I also don't think putting any CoA logic directly in l10n_xx  is a really good Idea unless you live in a very small country with only one single industry and no government agencies, nor banks...

**Comment by qdp-odoo** [comment]
Hi guys,

I just want to tell you that we will be working on a solution on the incoming weeks.

What I think, so far, is that we will define a test that will:
* for each localization module: create one company using that localization (will check that the CoA install isn't broken), and run tests located in that localization (if any)
* be run only in runbot nightly (once a day): because it will be time consuming and would increase a lot the current execution delay.

Hope that helps,

**Comment by nhomar** [comment]
@qdp-odoo 

Just as a comment to ensure we are all in the same line. We have some topics to be solved which are strongly related.

1. The autoinstallation of the l10n_xx when country present is PERFECT I like the idea it is nothing bad on that, BUT use a default CoA which brake by default all athers is NOT ok, we need a fix for that.
2. The fact of that by default l10n_xx are not being tested (that will be solved with what you just mentioned in runbot).
3. The fact that the current behavior need a manual interaction to create the db with the graphical interface due to the fact that the Country is not being setted (for me this is the more paifull one) all automated tools rely on the fact that you can use -i module -d database and you are forcing an extra step for that: patch with main company + -i module -d database, I really would like have again only one step not 2.

Thanks in advance for your feedback... Nice job dudes!

**Comment by blaggacao** [comment]
@nhomar If I understand Quentin correctly and read his suggestion carefully, I see all your points covered.

> for each localization module: create one company using that localization (will check that the CoA install isn't broken), and run tests located in that localization (if any)

Little attention has been brought to multi-company multi-localisation setups and I guess the current focus of most localisations is rather local, than global. Yet, customers are global, so I see this as an important step to get some traction to the localisation space and set the bases for an aligned evolution rather than competing and incompatible conceptualization. Great job, Quentin! Take the lead!

**Comment by nhomar** [comment]
Hello.

@qdp-odoo did get the time to work on this for v11.0 but we will find a solution in the close future.

In the mean while @blaggacao if you set the env variable COUNTRY on your CI environment and force install[ this module ](https://github.com/Vauxoo/server-tools/tree/11.0/company_country)as dependency in the base database you will solve the problem in a clean manner.

I hope it helps to you:

**Note:** We did not propose that as PR because we think it is not a clean generic solution, due to that works a little tricky around how we work definitively inside OCA, but if somebody find it useful, feel free to extract and make a proper PR.
