### ISSUE TITLE
Phantomjs test timeout in travis

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/maintainer-quality-tools#432]
Hi, this test[1] succeeds locally, but times out with the OCA travis config[2]. Is this a known issue?

```
        code = """
            setTimeout(function () {
                if (!$('.oe_list_button_import').is(":visible")) {
                    throw new Error('Import button is not accessible.');
                }
                console.log('ok');
            }, 3000);
        """
        link = '/web#action=%s' % self.env.ref('base.action_res_users').id
        with mute_logger('openerp.addons.base.res.res_users'):
            # Mute debug log about failing row lock upon user login
            self.phantom_js(
                link, code, "$('button.oe_list_add')",
                login=self.env.user.login)
```

[1] https://github.com/OCA/server-tools/pull/743/files#diff-42657ea13cced82fd0efda56ecf8fef0R26
[2] https://travis-ci.org/OCA/server-tools/jobs/203880321

**Comment by moylop260** [comment]
Locally what commands are you executing?

**Comment by moylop260** [comment]
Forge it, I can reproduce it using original travis image with travis2docker.
FYI I can't reproduce it using the image used from runbot.

Maybe is a issue with library versions:
travis image where is reproduce it:
`phantomjs --version`
`1.9.8`

vx image where is not reproduce it:
`phantomjs --version`
`1.9.0`

What version do you have locally?

**Comment by StefanRijnhart** [comment]
That's it. It works fine on 1.9.7. I have another machine with 2.1.1, and that version does not stop execution upon 'throw Error' so it times out instead of falsifying the behaviour. Another difference is that my waiting condition _$('button.oe_list_add')_ suddenly evaluates to true before it is loaded and I needed to switch to  _$('button.oe_list_add').**length**_.

Thanks for your help!

**Comment by StefanRijnhart** [comment]
Still not working. It works locally with phantomjs 2.1.1 and
```
bin/start_odoo  -d test_base_import_security_group -i base_import_security_group --test-enable --stop-after-init --addons-path=../odoo/addons,../server-tools --workers=0
```
(config file is empty)

While on a travis config with phantomjs 2.1.1[1] I'm still getting the error timeout[2]

[1] https://travis-ci.org/OCA/server-tools/jobs/203995068#L272
[2] https://travis-ci.org/OCA/server-tools/jobs/203995068#L1890

**Comment by moylop260** [comment]
The real issue is:
 - A test using a external connection (phantomjs) with previous record modified.
 - PostgreSQL Server default version from travis 
 - `if` sentences from odoo for check postgresql version and change the behaviour

If you see [record-modified](https://github.com/StefanRijnhart/server-tools/blob/03acf5d3ed9eca6d4faca07f219a7f511cd9860d/base_import_security_group/tests/test_base_import_security_group.py#L39) we have
```python
    def test_01_in_group(self):
        """ Show import button to users in the import group """
        self.env.user.groups_id += self.group  # record modified
        self.assertTrue(self.env.user.has_group(self.group_ref))
        self.has_button_import()  # here we are calling phantomjs method
        self.assertTrue(self.load())
```

If we run:
`docker run -it --rm quay.io/travisci/travis-python /bin/bash -c "/etc/init.d/postgresql start"`
You will see that the default PostgreSQL Server for travis is the version 9.1

- ![screen shot 2017-02-22 at 12 16 35 am](https://cloud.githubusercontent.com/assets/6644187/23199292/3c7cbd2e-f893-11e6-81b7-21123350b77c.png)


If we run:
`grep -n "\.server_version" ~/odoo-8.0 --include=*.py`
You will see validations for a particular version of PostgreSQL Server 
 - ![screen shot 2017-02-22 at 12 10 38 am](https://cloud.githubusercontent.com/assets/6644187/23199168/690a5c30-f892-11e6-8fad-8094e6d97818.png)

Then if we are using postgresql 9.1 the error is reproduced.
If you are using postgresql 9.3 the error is not reproduced.

You can review the following video with the problem and the fix using the [default travis docker image](https://quay.io/repository/travisci/travis-python) plus travis2docker:

[![IMAGE ALT TEXT](http://img.youtube.com/vi/PGYwpH8dURU/0.jpg)](http://www.youtube.com/watch?v=PGYwpH8dURU "Video Title")


You can see how to change postgresql default version for travis build from: [addons: postgresql: "9.4"](https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version)

**Comment by lmignon** [comment]
@moylop260 I've tested your proposal with https://github.com/acsone/web/commits/10.0-mig-web_duplicate_visibility-lmi-bis but without success. Locally tests are successful but not on travis.
https://travis-ci.org/acsone/web/jobs/204090585

**Comment by StefanRijnhart** [comment]
:heart::heart::heart: Thank you @moylop260!

**Comment by moylop260** [comment]
@lmignon 
Your issue is a little different (and maybe the fix is different too).
The infinite loop from: https://travis-ci.org/OCA/server-tools/jobs/203880321 for https://github.com/OCA/server-tools/pull/743 was fixed using PostgreSQL Server 9.3 from https://github.com/OCA/server-tools/pull/746 build https://travis-ci.org/OCA/server-tools/builds/204088292

This is not your case for a output different to expected one.

**Comment by moylop260** [comment]
@StefanRijnhart 
FYI I saw a flaky error (random) using OCA/OCB if you rebuild it then works!
I don't know the reason but the infinite loop was fixed.

**Comment by moylop260** [comment]
@lmignon 
For your issue a upgrade of phantomjs is required.
Running the phantomjs command manually using phantomjs-1.9.0 and 2.1.1 I received the following output:

 - ![screen shot 2017-02-22 at 2 42 42 am](https://cloud.githubusercontent.com/assets/6644187/23203323/a8a6d8fe-f8a7-11e6-9bc5-cc62ff30e8b4.png)

The MutationObserver is supported for >phantomjs-2.0
More info https://github.com/ariya/phantomjs/issues/10715

**Comment by lmignon** [comment]
@moylop260 thank you for your investigation unfortunately that's seems to be not enough... https://travis-ci.org/acsone/web/jobs/204130803 
https://github.com/acsone/web/blob/10.0-mig-web_duplicate_visibility-lmi-bis/.travis.yml

**Comment by moylop260** [comment]
Maybe is not working fine the PATH...
What version of phantomjs you have locally (where works)?

**Comment by moylop260** [comment]
@lmignon 
Now is other error, I saw a incompatibility with `web_export_view` module.

If I use `EXCLUDE=web_export_view` works fine:
 - ![screen shot 2017-02-22 at 10 52 12 am](https://cloud.githubusercontent.com/assets/6644187/23221968/1015db68-f8ec-11e6-911e-f94014d333b1.png)

if I just install `INCLUDE=web_duplicate_visibility` module works fine:
 - ![screen shot 2017-02-22 at 10 51 40 am](https://cloud.githubusercontent.com/assets/6644187/23221969/101b5778-f8ec-11e6-8891-7db507dcfc54.png)

if I install `web_duplicate_visibility` and `web_export_view` modules together fails:
 - ![screen shot 2017-02-22 at 10 52 48 am](https://cloud.githubusercontent.com/assets/6644187/23221983/1cb11324-f8ec-11e6-8872-7570d1f73b61.png)

I have created the https://github.com/OCA/web/pull/563 to test my hypothesis with a green result installing just `web_duplicate_visibility` with a green result:
 - https://travis-ci.org/OCA/web/jobs/204270953#L566

NOTE: The phantomjs upgrade is working and is required too.

**Comment by lmignon** [comment]
@moylop260 Thank you for your help!!! Do I have to modify travis.yml to test web_duplicate_visibility alone?

**Comment by moylop260** [comment]
@lmignon That is a fast solution.
However IMHO It's better dual compatibility.

**Comment by lasley** [comment]
The downfall of isolating the modules is that only the first TESTS=1 in the Travis file is built in Runbot. This means that modules in isolated build-sets are not functionally testable in Runbot 😦

**Comment by moylop260** [comment]
Yeah, we could use a `if RUNBOT` or something similar
But I think that we could have a solution for dual compatibility (I don't know)
Maybe @Yajo could help us

**Comment by Yajo** [comment]
Sorry I read the thread but don't understand the problem (nor where could I help) 😅

**Comment by moylop260** [comment]
@yajo
You are right we are hijacking this issie for other matter
Sorry

The PR
https://github.com/OCA/web/pull/563 fails the phantomjs tests if web_duplicate_visibility and web_export_view modules are installed together.

The question is:
Is possible run the phantomjs tests without errors for these modules?
