### ISSUE TITLE
Incorrect Build Success

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#447]
This build should have failed, but passed:
https://travis-ci.org/OCA/project/jobs/237996931#L1107

**Comment by dreispt** [comment]
I guess thus @dreispt guy is to [blame](https://github.com/OCA/maintainer-quality-tools/commit/ee9aef3650b3c08922bc363c96612ac3dd2b8d70).
For reference, #43 motivated the change.

**Comment by dreispt** [comment]
@sbidoul [This](https://travis-ci.org/OCA/management-system/jobs/215216204#L550) build has the same missing dependency error, yet it fails!

It is two months old. Maybes something changed in between? 🤔 
Not the code you pointed to, surely...

**Comment by dreispt** [comment]
Might be related to https://github.com/OCA/maintainer-quality-tools/commit/be28ef3ec0cb13c96b50b0a639f1bc316c64120c
@pedrobaeza should it be reverted?

**Comment by sbidoul** [comment]
@dreispt in my experience the Odoo exit code is not reliable. So detecting ERROR would be a good thing to do IMO.

**Comment by moylop260** [comment]
What about use the [runbot's regular expression](https://github.com/odoo/odoo-extra/blob/9e1ff15449ba56fdf1d3cc8993dec428da54c8dd/runbot/runbot.py#L46-L47) but for MQT?

```python
_re_error = r'^(?:\d{4}-\d\d-\d\d \d\d:\d\d:\d\d,\d{3} \d+ (?:ERROR|CRITICAL) )|(?:Traceback \(most recent call last\):)$'
_re_warning = r'^\d{4}-\d\d-\d\d \d\d:\d\d:\d\d,\d{3} \d+ WARNING '
```

We will have all cases covered.

**Comment by moylop260** [comment]
Using the same output from https://travis-ci.org/OCA/project/jobs/237996931#L1107

The result is:

`python -c "import re;_re_error = r'^(?:\d{4}-\d\d-\d\d \d\d:\d\d:\d\d,\d{3} \d+ (?:ERROR|CRITICAL) )|(?:Traceback \(most recent call last\):)$';regexp = re.compile(_re_error, re.M);print '\n'.join(regexp.findall(open('job_test_all.txt').read()))"`

```bash
2017-05-31 23:36:23,512 5776 ERROR
2017-05-31 23:36:38,510 5776 ERROR
2017-05-31 23:36:38,514 5776 ERROR
```

For all odoo's versions

**Comment by dreispt** [comment]
@moylop I have no doubts theat your RE works beatifully, but what puts me off is that it is unreadable and, at least for me, close to unmaintainable. I like the "explicit is better than implicit" mantra.

**Comment by moylop260** [comment]
The use of a `if` for each case is creating many issues related with false green from a long time.

You can understand this regex playing with the following link that I have created for you:
https://regex101.com/r/OGRjhs/1

And currently we are [seudo-using regex](https://github.com/OCA/maintainer-quality-tools/blob/be28ef3ec0cb13c96b50b0a639f1bc316c64120c/travis/test_server.py#L61-L64)


 - We will fix false red results
 - We will clean a few lines of code unnecessary
 - Reduce maintainable because this regex have covered all cases and we don't need add one by one after detect that is not working and create a new issue like as: 
 - https://github.com/OCA/maintainer-quality-tools/issues/98
 - https://github.com/OCA/maintainer-quality-tools/issues/148
 - https://github.com/OCA/maintainer-quality-tools/issues/176
 - https://github.com/OCA/maintainer-quality-tools/issues/179
 - https://github.com/OCA/maintainer-quality-tools/issues/348

If you search a issue related with a false green from runbot using this regex you will get zero.

**Comment by dreispt** [comment]
Independently of my concerns, we will surely be better with with the regex than with the current state.
IMO you can propose it to MQT. If you could include your link in a comment, it would be helpful for interpretation and maintenance.

**Comment by dreispt** [comment]
@moylop260 does it also catch failing tests?

**Comment by moylop260** [comment]
@JesusZapata Could you create a PR to change the current log process to use regex like as runbot?

**Comment by nhomar** [comment]
Let's continue the discussion into the PR #476 itself, to close, re-plan or merge the change.
