### ISSUE TITLE
New check appears "magically": E722 do not use bare except

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#496]
Example: https://travis-ci.org/OCA/OpenUpgrade/builds/291659303#L562

It can be because of a new flake8 version. 

@moylop260 any clue?

**Comment by moylop260** [comment]
Yes it is because a combination of
1) We dont have freezed flake8 version
2) We have disabled current checks (instead of enable them)

So if a new flake8 is released with a new check you need add in the configuration files the new check in order to disable it.
Or you can freeze the version of flake8 in order to avoid magically new check appears.
