### ISSUE TITLE
Strange problem in Transifex + odoo/odoo builds in Travis

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#539]
I'm experimenting a strange problem in both stages in several repositories. Examples:

https://travis-ci.org/OCA/bank-payment/builds/366461895
https://travis-ci.org/OCA/l10n-spain/builds/366268879

It coincides in time more or less with the arrival of #537. Is there any relation?

@moylop260 @StefanRijnhart @mreficent

**Comment by sbidoul** [comment]
My bet is that github has had a timezone bug when preparing the current tar.gz for 10.0. It does not seem to be related to #537

**Comment by pedrobaeza** [comment]
But the date seems correct...
```
time stamp 2018-04-14 14:29:07
```
and it's only happening in that build, not in OCA/OCB one. As said, very strange...

**Comment by pedrobaeza** [comment]
It's only happening on 10.0 build, but not the rest (I have seen 9.0 and 11.0 successful builds). Maybe something incorrect in GitHub tar? How is it obtained?

**Comment by pedrobaeza** [comment]
Thanks for checking. Then, I can close this.

**Comment by pedrobaeza** [comment]
What are the advantages of using that method?

**Comment by moylop260** [comment]
Advantages using git clone instead of tar file:
 - Running MQT script from your local machine or docker you can re-user the odoo repository to upgrade it (`git pull`)
 - Using `git depth=10` like as travis-ci uses we will have a faster download.
 - We can know the odoo sha of the build if there is a error you can reproduce it using the same sha.
 - We can verify a custom change applied to dooo repository if there are a `sed` executed or `patch` using `git diff` and return to original state.

And the other one, remove this flaky error using tar files.

**Comment by pedrobaeza** [comment]
Well, let's go with that then! You're the master of MQT, so you know where to touch.

**Comment by moylop260** [comment]
FYI https://github.com/OCA/maintainer-quality-tools/pull/540
